blog/urls.py
from django.urls import path
from blog.views import (
    home_view,
    new_blog_view,
    blog_list_view
)



app_name = 'blog'


urlpatterns = [
    path('', home_view, name='home'),
    path('new/blog', new_blog_view, name='new-blog'),
    path('blogs', blog_list_view, name='blogs')
]

djang_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse


def home_view(request):
    return render(request, 'blog/home.html', context=None)

def blog_list_view(request):
    blog_list = [
        {'id': 1, 'title': 'blog title', 'content': 'blog content'},
        {'id': 2, 'title': 'blog title ', 'content': 'blog content'},
        {'id': 3, 'title': 'blog title ', 'content': 'blog content'},
        {'id': 4, 'title': 'blog title ', 'content': 'blog content'},
        {'id': 5, 'title': 'blog title ', 'content': 'blog content'}
    ]
    data = {
        'blog_list': blog_list
    }
    return JsonResponse(data)

def new_blog_view(request):
    blog = {'id': 1, 'title': 'New Blog Title', 'content': 'New blog content'}
    data = {
        'id': blog['id'],
        'title': blog['title'],
        'content': blog['content']
    }
    return JsonResponse(data)

blog/templates/blog/home.html
{% extends 'blog/index.html' %}
{% load static %}


<title>{% block title %} Home {% endblock title %}</title>



{% block content %}
    <!-- hero image -->
    <div class="hero-img">
        <img id='hero-img' src="{% static 'blog/images/img1.webp' %}"  alt="">
        <div class='hero-img-background-overlay'>
            <div class='hero-img-text-container'>
                <div class='hero-img-text-wrapper'>
                    <h1>What is on your mine?</h1>
                    <p>
                        Share, Learn, Chat with others users like you.
                    </p>
                    <div>
                        <a href="">Get started</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mobile-hero-img">
        <img id='mobile-hero-img' src="{% static 'blog/images/img2.webp' %}" alt="">
        <div class='mobile-hero-img-background-overlay'>
            <div class='mobile-hero-img-text-container'>
                <div class='mobile-hero-img-text-wrapper'>
                    <h1>What is on your mine?</h1>
                    <p class="hero-text">
                        Share, Learn, Chat with others users like you.
                    </p>
                    <p class='hero-text2'>Lorem Ipsum is simply dummy text</p>
                    <div>
                        <a href="">Get started</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end of hero image -->

    <!-- scroll up btn -->
    <div class="scroll-up-container">
        <a class='scroll-up' href="#header"><i class="fas fa-chevron-up"></i></a>
    </div>
    <!-- end of scroll up btn -->

    <!-- main content -->
    <div id='contents' class="contents">
        <div><h1>All contents</h1></div>
        <!-- 1 content -->
        <div id="content1">
            <h1>What is Lorem Ipsum?</h1>
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                when an unknown printer took a galley of type and scrambled it to make a type 
                specimen book.
            </p>
        </div>
        <!-- 1 content -->
        <!-- 2 content -->
        <div>
            <h1>What is Lorem Ipsum?</h1>
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                when an unknown printer took a galley of type and scrambled it to make a type 
                specimen book.
            </p>
        </div>
        <!-- 2 content -->
        <!-- 3 content -->
        <div>
            <h1>What is Lorem Ipsum?</h1>
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                when an unknown printer took a galley of type and scrambled it to make a type 
                specimen book.
            </p>
        </div>
        <!-- 3 content -->
        <!-- 4 content -->
        <div>
            <h1>What is Lorem Ipsum?</h1>
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                when an unknown printer took a galley of type and scrambled it to make a type 
                specimen book.
            </p>
        </div>
        <!-- 4 content -->
        <!-- 5 content -->
        <div>
            <h1>What is Lorem Ipsum?</h1>
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                when an unknown printer took a galley of type and scrambled it to make a type 
                specimen book.
            </p>
        </div>
        <!-- 5 content -->
        <!-- 6 content -->
        <div>
            <h1>What is Lorem Ipsum?</h1>
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                when an unknown printer took a galley of type and scrambled it to make a type 
                specimen book.
            </p>
        </div>
        <!-- 6 content -->
        <!-- 7 content -->
        <div>
            <h1>What is Lorem Ipsum?</h1>
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                when an unknown printer took a galley of type and scrambled it to make a type 
                specimen book.
            </p>
        </div>
        <!-- 7 content -->
        <!-- 8 content -->
        <div>
            <h1>What is Lorem Ipsum?</h1>
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                when an unknown printer took a galley of type and scrambled it to make a type 
                specimen book.
            </p>
        </div>
        <!-- 8 content -->
    </div>
{% endblock content %}

blog/templates/blog/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- lobster google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
   
    <!-- roboto google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
    
    <!-- font awesome icons package-->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/all.css' %}">
    
    <!-- project css -->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header id="header">
        {% include 'blog/nav.html' %}
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <script type="text/javascript" src="{% static 'blog/main.js' %}"></script>
</body>
</html>

blog/templates/blog/nav.html
{% load static %}

<link rel="stylesheet" type='text/css' href="{% static 'blog/nav.css' %}">


<!-- large screen  -->
<div class="nav-bar">
    <nav class="nav-wrapper">
        <div class="brand-name-wrapper">
            <a href="{% url 'blog:home' %}">
                <span>A</span>
                <div>
                    <span class="l-span">IAILA</span>
                    <span>BLOG FORUM</span>
                </div>
            </a>
        </div>
        <form class='search-form' action="" method="GET">
            <input type="text" name="search" placeholder="Search by title or keyword">
            <button name='submit-search' type="submit">Search</button>
        </form>
        <div class="large-font-awesome-btns">
            <i class="fas fa-bars bars-btn-2"></i>
            <i class="fas fa-close close-btn-2"></i>
        </div>
        <ul class="nav-items">
            <li class="profile-container">
                <a class="user-profile" href="">
                    <img src="{% static 'blog/profile_img/dog.webp' %}" alt="">
                    <div class="user-info">
                        <span>Username: Admin</span>
                        <span>Joined: Feb 12, 2022</span>
                        <div style="display: none;">
                            <span>Location: Philippines</span>
                            <span>Blogs: 10</span>
                            <span>Likes: 22</span>
                            <span>Following: 3</span>
                        </div>
                    </div>
                    <i class="fas fa-chevron-down profile-container-chevron"></i>
                </a>
            </li>
            <li><a href=""><i class="fas fa-home"></i>Home</a></li>
            <li><a href=""><i class="fa-solid fa-blog"></i>My blogs</a></li>
            <li><a href=""><i class="fas fa-sign-in"></i>Login</a></li>
            <li><a href=""><i class="fa-solid fa-user-plus"></i> Join</a></li>
        </ul>
    </nav>
</div>
<!-- end of large screen -->




<!-- mobile navigation bar -->
<div class="mobile-nav-bar">
    <div class="mobile-brand-name">
        <a href="{% url 'blog:home' %}">
            <span>A</span>
            <div>
                <span class="l-span">IAILA</span>
                <span>BLOG FORUM</span>
            </div>
        </a>
        <div class="font-awesome-btns">
            <i class="fas fa-bars bars-btn"></i>
            <i style="display: none;" class="fas fa-close close-btn"></i>
        </div>
    </div>
    <ul class="mobile-menu-items">
        <li>
            <a class="user-profile" href="">
                <img src="{% static 'blog/profile_img/dog.webp' %}" alt="">
                <div>
                    <span>Admin</span>
                    <span>Joined: Feb 12, 2022</span>
                </div>
            </a>
        </li>
        <li><a class='mobile-search' href=""><i class="fas fa-search"></i>Search</a></li>
        <li class='mobile-search-form'>
            <form action="" method="GET">
                <input type="text" name="search" placeholder="Search by title or keyword">
                <button name='submit-search' type="submit"><i class="fas fa-search"></i></button>
            </form>
        </li>
        <li><a href=""><i class="fas fa-home"></i>Home</a></li>
        <li><a href=""><i class="fa-solid fa-blog"></i>My blogs</a></li>
        <li><a href=""><i class="fas fa-sign-in"></i>Login</a></li>
        <li><a href=""><i class="fa-solid fa-user-plus"></i> Join</a></li>
    </ul>
</div>
<!-- end of mobile screen -->